language: rust

rust:
  - nightly
  - beta
  - stable

cache: cargo

script:
  - cargo build
  - cargo test
  - cargo build --features "numeric"
  - cargo test --features "numeric"

notifications:
    email: false
