language: rust

rust:
  - nightly
  - beta
  - stable
 
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --features "numeric" --verbose
  - cargo test --features "numeric" --verbose

notifications:
    email: false
