[package]
name = "data-buffer"
version = "0.4.2"
authors = ["Egor Larionov <egor.larionov@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A simple low-level data buffer type useful for IO and in homogeneous collections"

homepage = "https://github.com/elrnv/buffer"
repository = "https://github.com/elrnv/buffer"
readme = "README.md"

keywords = ["buffer", "io", "data"]

[badges]
travis-ci = { repository = "elrnv/buffer", branch = "master" }

[dependencies]
reinterpret = "0.1"
num-traits = { version = "0.2", optional = true }

[features]
numeric = ["num-traits"]
